version: '3.8'
services:
  # Django App
  backend:
   container_name: markt-MVP-container
   build: .
   volumes:
    - .:/app
   ports:
    - 8000:8000
   depends_on:
    - db
    - redis
  
  # Event Queue Kafka
  queue_auth:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db
  
  # Database (PostgreSQL)
  db:
   image: postgres
   container_name: markt-MVP_postgresql
   restart: always
   environment:
      POSTGRES_DB: markt-MVP
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
   ports:
    - 5432:5432
   volumes:
      - .dbdata:/var/lib/postgresql
  
  # Redis Cache
  redis:
    image: redis
    container_name: markt-MVP_redis
    ports:
      - 6379:6379