# Generated by Django 4.2.2 on 2023-07-24 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_addresses'),
        ('orders', '0002_rename_taxprice_order_tax_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.addresses'),
        ),
    ]
