# Generated by Django 4.2.2 on 2023-07-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_remove_wishlist_products_wishlist_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
