# Generated by Django 4.2.2 on 2023-09-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_username'),
        ('lists', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, to='user.client'),
        ),
        migrations.AlterField(
            model_name='favoritecompanies',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.client'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.client'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, to='user.client'),
        ),
    ]
