# Generated by Django 4.2.2 on 2023-07-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsubscribers',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
