# Generated by Django 4.2.2 on 2023-07-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
