# Generated by Django 4.2.2 on 2023-07-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_orderitem'),
        ('lists', '0004_alter_orderhistory_orders'),
        ('user', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
