# Generated by Django 4.2.2 on 2023-07-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_shippingaddress_order_delete_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_media',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
