# Generated by Django 4.2.2 on 2023-07-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addresses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
