# Generated by Django 4.2.2 on 2023-07-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='store_logo'),
        ),
    ]
