# Generated by Django 4.2.2 on 2023-07-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_user_addresses_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_addresses',
            field=models.ManyToManyField(blank=True, related_name='user_addresses', to='user.addresses'),
        ),
    ]
