# Generated by Django 4.2.2 on 2023-07-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_user_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_addresses',
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
