# Generated by Django 4.2.2 on 2023-07-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_user_user_addresses_delete_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('ROPA', 'Ropa'), ('JOYERIA', 'Joyeria'), ('DECORACION', 'Decoracion'), ('MASCOTAS', 'Mascotas')], max_length=20, null=True),
        ),
    ]
