# Generated by Django 4.2.2 on 2023-07-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('TOY', 'Toy'), ('CLOTHES', 'Clothes')], max_length=200),
        ),
    ]
