# Generated by Django 4.2.2 on 2023-07-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='clothing_size_stock',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
