# Generated by Django 4.2.2 on 2023-07-23 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_inventory_clothing_size_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
