# Generated by Django 4.2.2 on 2023-07-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.BooleanField(null=True),
        ),
    ]
