# Generated by Django 4.2.2 on 2023-07-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', null=True),
        ),
    ]
