# Generated by Django 4.2.2 on 2023-07-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_clothing_size_stock_inventory_size_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
    ]
